### PR TITLE
Add multilingual support (multiple dictionaries)

### PR DESCRIPTION
**Pull request by nightuser**
Initial implementation of multilingual spellchecking. Doesn't work on OS X yet, as I don't have any Macs right now.

### CODE REVIEW

**Comment by zcbenz** [comment]
👍

**Comment by zcbenz** [comment]
Sorry I just realized there is another huge PR #50 waiting there, I'm reseting the master branch and will revisit this PR later.

**Comment by paulcbetts** [comment]
I think that my PR breaks the concept of this one - @nightuser, what are you using multiple dictionary support for? Maybe I'm missing a scenario here

**Comment by nightuser** [comment]
Well, I'm writing my thesis in Sublime because of similar multilingual support. It's mainly written in Russian, but has many English terms.I don't think that it'd be hard to implement that in your version, as I've borrowed the idea from Chromium (it's supporting multilingual spellcheck since August). I'll look into your PR soon.--Regards,Svyatoslav Gryaznov18:58, 1 июня 2016 г., Paul Betts <notifications@github.com>:I think that my PR breaks the concept of this one - @nightuser, what are you using multiple dictionary support for? Maybe I'm missing a scenario here —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by nightuser** [comment]
@paulcbetts I've forgot to mention you in the original version of the post above. And I don't know whether  notification has been sent to you.

**Pull request merged**
