### PR TITLE
Fix for v8 in node 12.

### PR DESCRIPTION
**Pull request by goddessfreya**
Signed-off-by: Hal Gentz <zegentzy@protonmail.com>

⚛👋 Hello there! Welcome. Please follow the steps below to tell us about your contribution.

1. Copy the correct template for your contribution
  - 🐛 Are you fixing a bug? Copy the template from <https://bit.ly/atom-bugfix-pr>
  - 📈 Are you improving performance? Copy the template from <https://bit.ly/atom-perf-pr>
  - 📝 Are you updating documentation? Copy the template from <https://bit.ly/atom-docs-pr>
  - 💻 Are you changing functionality? Copy the template from <https://bit.ly/atom-behavior-pr>
2. Replace this text with the contents of the template
3. Fill in all sections of the template
4. Click "Create pull request"

### CODE REVIEW

**Comment by radenkovic** [comment]
just to check if this is going to be merged anytime soon? Thanks!

**Comment by johnjjung** [comment]
+1 checking if this is going to be merged too please

**Comment by shahan312** [comment]
+1 Will this be merged soon? Thanks!

**Comment by TonyWuu** [comment]
Bump. Any plans to get it merged?

**Comment by goddessfreya** [comment]
I'm not exactly sure who still has commit access to this repo and who the maintainers are, so, uhhh, I guess I can try pinging everybody who's ever merged a commit here before?

cc @rafeca @smashwilson @maxbrunsfeld @nathansobo @zcbenz @kevinsawicki @lee-dohm @daviwil @anaisbetts @damieng @joefitzgerald I guess :woman_shrugging:

**Comment by bendemboski** [comment]
FYI, for folks waiting for this, I've been maintaining a fork, [spellchecker-prebuild](https://www.npmjs.com/package/spellchecker-prebuild) that is a drop-in replacement (the same code), but with prebuilt binaries. It has this fix rolled into it, and now has Electron 7-compatible binaries published, so you can use it with Electron 7.

**Comment by goddessfreya** [comment]
Sweet. I was personally planning to maintain a fork at [goddessfreya/node-spellchecker](https://github.com/goddessfreya/node-spellchecker/) until #130 gets merged in. Maybe we can roll our changes in together?

**Comment by bendemboski** [comment]
Yeah, I'm game, although unsure of the practical aspects. [It looks like](https://github.com/atom/node-spellchecker/pull/126#issuecomment-531044471) I'll be maintaining a prebuild fork indefinitely, and I have `spellchecker-prebuild` on npm pointing to my fork, so I'm loath to switch off my fork because of the extra work/fiddling it would entail.

Also, I have some hesitation about applying changes before they are released in `node-spellchecker` because then the versioning story gets confusing, and prebuilds kinda rely on version numbers and releases to function, so it's not as easy to using a git URL or something.

So I'm unsure of how we would do this, although very open to ideas...

**Comment by vladimiry** [comment]
Btw it also works well with Electron v8 (currently 8.0.0-beta.5).

**Pull request closed without merging**
